### ISSUE TITLE
Crash on Particle Load - Ver. 1.5.0 - MC 1.18

### ISSUE THREAD

**Issue by therealleopardg** [PigCart/particle-rain#13]
I'm pretty sure that an infrequent crash I'm getting is being caused by Particle Rain trying to access a specific float value. I'm not sure what significance the pig cart has, but as far as I'm aware there aren't any in the world. Let me know if I can provide any more information. Below is the log:

>Unreported exception thrown!
>java.lang.IllegalAccessError: class pigcart.particlerain.WeatherParticleSpawner tried to access private method 'float >net.minecraft.class_1959.method_21740(net.minecraft.class_2338)' (pigcart.particlerain.WeatherParticleSpawner and >net.minecraft.class_1959 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4ce7fffa)
>	at pigcart.particlerain.WeatherParticleSpawner.update(WeatherParticleSpawner.java:43)
>	at pigcart.particlerain.ParticleRainClient.onTick(ParticleRainClient.java:50)
>	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
>	at net.minecraft.class_310.handler$zfb000$onEndTick(class_310.java:6497)
>	at net.minecraft.class_310.method_1574(class_310.java:1807)
>	at net.minecraft.class_310.method_1523(class_310.java:1086)
>	at net.minecraft.class_310.method_1514(class_310.java:733)
>	at net.minecraft.client.main.Main.main(Main.java:236)
>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
>	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
>	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
>	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
>Process crashed with exit code -1

**Comment by EysseW** [comment]
It would be pretty nice if you can fix this tho, I love the mod

**Comment by Flogah** [comment]
The author is called pigcart lmao

**Comment by PigCart** [comment]
dunno why i was an ass and just ignored all these reports, sorry! 1.18.2 was never supported by me. 1.19 is now available on curseforge and modrinth, anyone still wanting 1.18.2 should check Ocelot's fork, build was triggered by Hendric-Shen here: https://github.com/Hendrix-Shen/particle-rain/actions/runs/2535661004
