### ISSUE TITLE
[BUG | 1.18.2] Game crashes upon world load

### ISSUE THREAD

**Issue by LonelySauce** [PigCart/particle-rain#15]
Minecraft Version: 1.18.2
Modloader: Fabric
Modloader Version: 0.13.3-1.18.2
Mod Version: particle-rain-2.0.0.jar

Steps to reproduce:

1. Launch the game with the mod active
2. Create or join a world where it is currently raining
3. Game should crash almost immediately

Expected Behavior: My game should not have crashed.

Demonstrated Behavior: Game crashes on world load, probably because it was raining in my world when I had joined back in 🙄

Crash Report: https://pastebin.com/QmDi7agp

Look I know this mod has a spiritual successor and all but that successor has terrible performance issues. My FPS tanks HARD from 200 to around 40 without the particle culling mod (because it hasn't been updated yet).

Essentially, I just want to see if this mod makes my FPS situation any better since it does look pretty nice compared to the alternative that was presented and hopefully won't kill my framerate.

**Comment by PigCart** [comment]
dunno why i was an ass and just ignored all these reports, sorry! 1.18.2 was never supported by me. 1.19 is now available, anyone still wanting 1.18.2 should check Ocelot's fork, build was triggered by Hendric-Shen here: https://github.com/Hendrix-Shen/particle-rain/actions/runs/2535661004
