### ISSUE TITLE
Awesome mod! but I do have an issue with the door and rain sound effects.

### ISSUE THREAD

**Issue by Belmoreworld** [PigCart/particle-rain#20]
I found out what mod causes the problem it was  your  et_futurum_requiem mod and the lord of the rings mod. for some reason they effect minecraft in a way where the sound effect for rain is turned off and same for the opening sound effect for the doors, trap doors for both mods. I am not sure why it happens but it may do with the code for both mods due to having the same set of doors. I am not an expert of coding so I can't really tell what would be happening but i just have a feeling it may be something between the programing for the door features.

just hoping if there is a way to have this fixed

if there is not then I will just simply remove the lord of the rings mod. (even though it does add a bit more stuff that i would like to keep) or I could just ignore the bug entirely.

hope to hear from you soon or anyone that can help.

**Comment by PigCart** [comment]
I am not the author of et_futurum_requiem so I think you might be in the wrong place. I'm not sure what you're trying to describe but it doesn't sound like something Particle Rain would be causing.
