### ISSUE TITLE
no rain particle when turning particle rain off

### ISSUE THREAD

**Issue by Thefatsparrow** [PigCart/particle-rain#23]
as it says in title when you turn particle rain off in the config there is no rain all together.

i like the snow and the desert particles but not very much the rain any way to fix this or is it a bug?

**Comment by Thefatsparrow** [comment]
version 1.20 but also the bug happened in 1.19.2

**Comment by PigCart** [comment]
eh I had a look but in vanilla rain and snow are rendered together and it looks like it'd be a hassle to seperate them.
I could add an option to turn all the vanilla weather back on but not individually.

**Comment by Thefatsparrow** [comment]
well that sucks so i can have one or the other! 

also any chance  you could add a setting for vanilla rain? what i mean is the same rain thats already in the mod but just vanilla textures. with shaders it does not look right it did look amazing on 1.19.2 though whats changed since 1.19.2?

**Comment by Thefatsparrow** [comment]
or what about making another mod called "particle sand" were its just sand particles and no rain or snow

**Comment by Thefatsparrow** [comment]
or is can you make a way to just use the vanilla particle for rain? so its compatible with shaders

**Comment by PigCart** [comment]
there is no vanilla particle. It's just a scrolling image.
I will add a config option to re-enable vanilla weather.
Shaders are working fine for me. If you're having problems please make a new issue with a proper description and game log
