### ISSUE TITLE
shader issue on 1.20

### ISSUE THREAD

**Issue by Thefatsparrow** [PigCart/particle-rain#24]
running quilt which is just optimised fabric so quilt is not the issue quilt also can run fabric mods as it runs on fabric

rain not right with complementary shaders

just looks like normal rain on 1.20. ive also tested it on fabric its still the same and annoying

the colour is just default vanilla 

![2023-06-29_23 01 57](https://github.com/PigCart/particle-rain/assets/86117177/c43ce087-1dfd-4d9a-9aa8-7d73bf4937ed)

**Comment by Thefatsparrow** [comment]
turning on shaders does not change rain like it does with vanilla rain

**Comment by Thefatsparrow** [comment]
[latest.log](https://github.com/PigCart/particle-rain/files/11910834/latest.log)

theres my log for you

**Comment by PigCart** [comment]
shader support will vary - complementary reimagined seems to handle mostly translucent particle textures differently to normal particles so I can tweak the texture to fix that.
shaders aren't going to override the colors of particles but I can add options to the config for that.

**Comment by Thefatsparrow** [comment]
bro your a legend! when will the update be?

**Comment by Thefatsparrow** [comment]
bro your a legend! thanks man
