### ISSUE TITLE
Command particles are black

### ISSUE THREAD

**Issue by BotBoi2000** [PigCart/particle-rain#25]
I'm on 1.20.1 (Mod Version 2.0.6) Minecraft and when I use the /particle command the particles are black. Other than the dependent mods there are no other mods.
![2023-07-06_19 55 55](https://github.com/PigCart/particle-rain/assets/103793962/5036dfef-180b-4033-9f27-5a068829e559)

**Comment by PigCart** [comment]
nice catch.
The particle command is trying to add velocity to the particles when it spawns them.
It turns out I've been using particle velocity to set the color this whole time, so the command screws up the color instead of setting the velocity.
will work on a fix.
