### ISSUE TITLE
[2.0.7] Crash loading Minecraft

### ISSUE THREAD

**Issue by SAJewers** [PigCart/particle-rain#26]
[crash-2023-07-08_20.41.41-client.txt](https://github.com/PigCart/particle-rain/files/11992602/crash-2023-07-08_20.41.41-client.txt)

2.0.6 works fine.

**Comment by PigCart** [comment]
Caused by Particle Tweaks.
It has a mixin that broke because I restructured some minor stuff last update.
You can report it in their curseforge comments I guess: https://www.curseforge.com/minecraft/mc-mods/particle-tweaks/comments
