### ISSUE TITLE
(1.20.1) [Bug] When using any season mod, rain is rendered in winter instead of snow.

### ISSUE THREAD

**Issue by MidasMischief** [PigCart/particle-rain#32]
If you set the season to winter when using any season mod, rain is rendered instead of snow but snow layers still are placed, not a game breaking bug, but takes away from the immersion.

**Comment by PigCart** [comment]
Thanks for taking a look! I actually only need to make a trivial change because Serene Seasons handles this very sensibly but I won't promise support for other season mods.
