### ISSUE TITLE
[backport] fixes for 1.21 for 1.20.1 fabric

### ISSUE THREAD

**Issue by PixelatedBruh** [PigCart/particle-rain#41]
Hello it would be nice to have the fixes you made backported to 1.20.1 as that is the most popular modded version (most big mods are on this version still)

**Comment by MihanDeNoob** [comment]
Indeed

**Comment by An0therOne** [comment]
does these fixes include fixing the bug when rain particles don't appear unless in superflat worlds? cause' I'm having that issue as of the moment

**Comment by PigCart** [comment]
oh! Forgot this issue was here. Completed with #45 

@An0therOne write a new issue and include your game log and i will take a look. sounds like itll be a mod incompatibility
