### ISSUE TITLE
Incorrect checking for Connector instances, cannot load because fails check for clothconfig2 when clothconfig2 is present

### ISSUE THREAD

**Issue by Barerock** [PigCart/particle-rain#44]
Using Connector and Particle Rain, Particle Rain fails its version check for Cloth Config in the Forge environment even though it is present.

![image](https://github.com/user-attachments/assets/1b81d10b-227c-4fa2-aaf0-4bbd96ee2f46)

**Comment by Barerock** [comment]
![image](https://github.com/user-attachments/assets/6912139f-f808-4941-b880-12a6fe463630)

**Comment by PigCart** [comment]
sinatyra connector is out of my hands. if it works, it works.
you probably need the fabric version in addition to, or instead of, the forge version of cloth config.

**Comment by Barerock** [comment]
Contrary, I have used previous versions of this mod without this problem. This IS the official version of cloth config, see the compatibility markers on it? And by Shedaniel? That's it. There isn't another version.
