### ISSUE TITLE
Particles not generating normally

### ISSUE THREAD

**Issue by An0therOne** [PigCart/particle-rain#47]
Particles not appearing when raining in normal worlds, but in superflat worlds they do appear, I don't know why this happens.

https://mclo.gs/Sol7Vcy

**Comment by PigCart** [comment]
Change the maximum particle count in particle rain's settings to a higher number.

Particle rain stops spawning when there are too many particles in the world to prevent lag. A mod in that modpack is spawning an absurd amount of particles (5000+) throughout the world which is making particle rain stop spawning entirely.

**Comment by An0therOne** [comment]
do you happen to know which mod is spawning said absurd amount of particles?

**Comment by PigCart** [comment]
no

**Comment by An0therOne** [comment]
oh
