### ISSUE TITLE
Rain is not affected by shaders

### ISSUE THREAD

**Issue by Redls07** [PigCart/particle-rain#51]
Rain from Particle Rain is not affected by shaders (vanilla rain/Particle Rain)
![2024-10-06_16 20 21](https://github.com/user-attachments/assets/1449329a-e920-4fcc-8e3d-d3262c8ca6ea)
![2024-10-06_16 19 56](https://github.com/user-attachments/assets/d8c1ee1a-defa-4eef-9bfe-76c437a16e94)

**Comment by PigCart** [comment]
this is what the color option in the config is for

**Comment by Redls07** [comment]
@PigCart The color option allows you to change only the color of the particles, while shaders change their transparency

**Comment by PigCart** [comment]
Will add transparency option.
