### ISSUE TITLE
(Suggestion) Opacity Setting

### ISSUE THREAD

**Issue by lenabees** [PigCart/particle-rain#57]
I used a resource pack that lowered the opacity of minecraft rain but I've since started using this mod because it looks much nicer, however I'd love the ability to lower the opacity for the particles so that I can keep them dense but less obstructive. Thanks!

**Comment by PigCart** [comment]
resourcepack support and an additional opactity slider are available in the upcomincg v3 update

**Comment by lenabees** [comment]
Sweet! Thank you
