### ISSUE TITLE
Crash at launch in 1.6.5

### ISSUE THREAD

**Issue by Blackwaiser** [PigCart/particle-rain#6]
Everithing is up to date and just the mod and the API are in the mod folder

fabric-loader-0.11.6-1.16.5
fabric-api-0.37.1+1.16
particle-rain+1.4

Crash report

https://pastebin.com/MTLNkS77

**Comment by PigCart** [comment]
should be fixed try the new file:
https://www.curseforge.com/minecraft/mc-mods/particle-rain/files/3420025
