### ISSUE TITLE
Crashes with the Emotecraft mod

### ISSUE THREAD

**Issue by Sckody** [PigCart/particle-rain#65]
Crashes with the Emotecraft mod. Causes Minecraft to crash and close, this happens to me when I fall into an ender chest filled with water, the latest version of Particle Rain and EmoteCraft is installed
![изображение_2024-12-18_192707692](https://github.com/user-attachments/assets/27b4199f-75a4-4c4e-82a5-a1f6cf6982a6)

**Comment by PigCart** [comment]
does this still happen in 3.0.2?

**Comment by Sckody** [comment]
No


сб, 21 дек. 2024 г. в 03:41, PigCart ***@***.***>:
