### ISSUE TITLE
[Suggestion] Make streak particles on block edges disappear in water

### ISSUE THREAD

**Issue by TheRealSomeRando** [PigCart/particle-rain#68]
Self-explanatory, when rain creates streak particles on blocks, they still persist when underwater, looking pretty strange. 
![2024-12-19_14 36 24](https://github.com/user-attachments/assets/51b73b2f-a822-4b6c-b619-7d79f5e6b5a8)

**Comment by PigCart** [comment]
spongebob mechanics!

(i completely missed this, nice catch. will put on the todo list)
