### ISSUE TITLE
Black and Pink Texture for Particles when jumping in water

### ISSUE THREAD

**Issue by puppie1997** [PigCart/particle-rain#69]
Here is my log file so you can see what mods I have installed. The pink and black particles only appear when I have Particle-Rain installed.
[latest.log](https://github.com/user-attachments/files/18215949/latest.log)
![ezgif-5-e78a93cf3d](https://github.com/user-attachments/assets/95710f17-2232-4166-8ac1-1c08f670951e)

**Comment by PigCart** [comment]
already fixed, download the latest version 3.0.2
