### ISSUE TITLE
Don't nest cloth config.

### ISSUE THREAD

**Issue by RDKRACZ** [PigCart/particle-rain#7]
This lib is highly popular and its size is huge. It gets included in many mods so the modpack with 80 mods is 40 MB bigger in size than needed.
Or maybe you can release an additional one without cloth?

**Comment by RDKRACZ** [comment]
Jar size would go down 1100 KB >> 280 KB

**Comment by PigCart** [comment]
mm good point, hadn't considered the impact on modpacks at all. Thanks

**Comment by YoshiRulz** [comment]
All the Modrinth releases since this change are missing the Cloth Config requirement.

**Comment by PigCart** [comment]
huh! added those now thanks
