### ISSUE TITLE
minecraft stuck on loading screen with the mod.

### ISSUE THREAD

**Issue by madaBoda** [PigCart/particle-rain#73]
That's it, minecraft gets stuck on the loading screen and i cannot do anything.

**Comment by madaBoda** [comment]
and logs: https://mclo.gs/WswLuRu

**Comment by Leclowndu93150** [comment]
java.util.concurrent.CompletionException: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:textures/particle/splash_\u0660.png

**Comment by madaBoda** [comment]
> java.util.concurrent.CompletionException: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:textures/particle/splash_\u0660.png

is that for me?

**Comment by Leclowndu93150** [comment]
for the dev

**Comment by PigCart** [comment]
Can you download unzip and try this version?
https://github.com/PigCart/particle-rain/actions/runs/12456678201/artifacts/2353760033

**Comment by madaBoda** [comment]
So i'm dumb, do i put both jar files?

**Comment by PigCart** [comment]
remove the old particlerain3.0.2 jar and put in the 3.0.4 one

**Comment by madaBoda** [comment]
It works! (btw i love this mod, thank you for it ^^)
