### ISSUE TITLE
Crash with Particle Tweaks

### ISSUE THREAD

**Issue by Liamgrayskull** [PigCart/particle-rain#82]
https://mclo.gs/ZqYKDlv

Game runs just fine without particle tweaks installed, but with the 1.20.1 v3.0.5 version, the game crashes on load with both mods running, displaying the above crash report (seems to be an issue with it not knowing how to apply particle fade or similar- is there a known way to exclude this?)

Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [particletweaks.mixins.json:client.particlerain.WeatherParticleMixin from mod particletweaks] from phase [DEFAULT] in config [particletweaks.mixins.json] FAILED during APPLY

https://modrinth.com/mod/particle-tweaks

**Comment by Leclowndu93150** [comment]
That's because both mods try to patch the same vanilla files which makes them incompatible

**Comment by PigCart** [comment]
@Liamgrayskull use particle tweaks 1.1.1. this is mentioned on particle rain's mod page.

> That's because both mods try to patch the same vanilla files which makes them incompatible

no. particle tweaks attempts to modify particle rain, which has changed significantly since particle tweaks last updated.
