### ISSUE TITLE
[Suggestion] Integration with mods that can change the cloud height

### ISSUE THREAD

**Issue by poqbox** [PigCart/particle-rain#88]
Rain particles no longer spawn above cloud height with this mod, but some mods, namely Better Clouds, allow for changing the cloud's spawn height. It'd be great to see integration with this mod or an option to toggle this feature. Another solution could be a setting to change the rain's maximum spawn height.

**Comment by PigCart** [comment]
these options already exist

**Comment by poqbox** [comment]
mb
